name: playground
services:
  directus:
    ports:
      - 8055:8055
    image: directus/directus:10.11
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: 255d861b-5ea1-5996-9aa3-922530ec40b1
      SECRET: 6116487b-cda1-52c2-b5b5-c8022c45e263
      ADMIN_EMAIL: system@maslio.com
      ADMIN_PASSWORD: system
